name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ต้องมี เพื่อให้ SonarCloud วิเคราะห์โค้ดได้ครบ

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@3d9f343d45711a0ab4b73b3c67288e3727a64755
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.organization=nittayajp31-create
            -Dsonar.projectKey=devjp31_sample-app
            -Dsonar.host.url=https://sonarcloud.io
